# Generated by Django 5.2.17 on 2026-08-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('batch_hash', models.CharField(max_length=64, unique=True)),
                ('receipt_count', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_ref', models.CharField(max_length=50, unique=True)),
                ('client_uuid', models.UUIDField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField()),
                ('receipt_device_id', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='intake.outlet')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='intake.collectionbatch')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('IGNORED_OLDER_VERSION', 'Ignored Older Version')], max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='intake.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROCESSED', 'Processed'), ('DUPLICATE_BATCH', 'Duplicate Batch')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='intake.collectionbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['recorded_at'], name='intake_coll_recorde_b2e0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['outlet'], name='intake_coll_outlet__7fbed5_idx'),
        ),
    ]
