# Generated by Django 5.2.17 on 2026-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_collectionbatch_collection_collectionaudit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='intake_coll_outlet__7fbed5_idx',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='outlet',
        ),
        migrations.AddField(
            model_name='collection',
            name='outlet_code',
            field=models.CharField(db_index=True, default='ZX', max_length=16),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['outlet_code'], name='intake_coll_outlet__72e9c6_idx'),
        ),
    ]
